restructure tracker
2110521-2563-1-Software-Architecture/TODO-term-project pull request #22
Opened 2020-11-28 11:51 UTC by CeylonT

- restructure directory
- remove unnecessary file
- add gin

2020-11-28 13:20 UTC, UtopiaBeam approved these changes

2020-11-28 13:27 UTC, UtopiaBeam requested changes

2020-11-28 13:27 UTC, UtopiaBeam commented on docker-compose.yml
>      container_name: todo-peer
Rename this to `todo-peer-0`

2020-11-30 09:48 UTC, CeylonT commented on docker-compose.yml
>      container_name: todo-peer
fixed

2020-11-30 09:49 UTC, merged